// examples/valtio/src/App.tsx
/* eslint-disable @typescript-eslint/no-misused-promises */
import { useEffect } from 'react';
import { useSnapshot } from 'valtio';
import { onError, printStore } from './commands';
import { exit } from '@tauri-apps/plugin-process';
import { increment, incrementNested, openStore, store } from './counter';
import { clearAutosave, setAutosave } from '@tauri-store/valtio/src/index.js';

export default function App() {
  const storeState = useSnapshot(store.state);

  useEffect(() => {
    const onKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        e.preventDefault();
        exit(0).catch(onError);
      }
    };

    window.addEventListener('keydown', onKeyDown);

    return () => {
      window.removeEventListener('keydown', onKeyDown);
    };
  }, []);

  useEffect(() => {
    store.start().catch(onError);
  }, []);

  return (
    <main>
      <div className="action">
        <button type="button" onClick={() => setAutosave(5000)}>
          Set Autosave
        </button>
        <button type="button" onClick={clearAutosave}>
          Clear Autosave
        </button>
      </div>

      <section id="counter">
        <p>
          Counter: {storeState.counter}
          Nested: {storeState.nested.foo.bar.baz}
        </p>
        <div className="action">
          <button type="button" onClick={increment}>
            Increment
          </button>
          <button type="button" onClick={incrementNested}>
            Increment Nested
          </button>
          <button type="button" onClick={store.start}>
            Start
          </button>
          <button type="button" onClick={store.stop}>
            Stop
          </button>
          <button type="button" onClick={store.save}>
            Save
          </button>
          <button type="button" onClick={store.saveNow}>
            Save Now
          </button>
          <button type="button" onClick={printStore}>
            Print
          </button>
          <button type="button" onClick={openStore}>
            Open
          </button>
        </div>
      </section>
    </main>
  );
}

// examples/pinia/src/App.vue
<script setup lang="ts">
import '../../assets/style.css';
import { onMounted } from 'vue';
import { onKeyDown } from '@vueuse/core';
import { openStore, useStore } from './counter';
import { onError, printStore } from './commands';
import { exit } from '@tauri-apps/plugin-process';
import { clearAutosave, save, saveNow, setAutosave } from '@tauri-store/pinia/src/index.js';

const store = useStore();
const { start, stop } = store.$tauri;

onKeyDown('Escape', () => {
  exit(0).catch(onError);
});

onMounted(() => {
  start().catch(onError);
});
</script>

<template>
  <main>
    <div class="action">
      <button type="button" @click="() => setAutosave(5000)">Set Autosave</button>
      <button type="button" @click="clearAutosave">Clear Autosave</button>
    </div>
    <section id="counter">
      <p>Counter: {{ store.counter }} Nested: {{ store.nested.foo.bar.baz }}</p>
      <div class="action">
        <button type="button" @click="store.increment">Increment</button>
        <button type="button" @click="store.incrementNested">Increment Nested</button>
        <button type="button" @click="start">Start</button>
        <button type="button" @click="stop">Stop</button>
        <button type="button" @click="save(store.$id)">Save</button>
        <button type="button" @click="saveNow(store.$id)">Save Now</button>
        <button type="button" @click="printStore">Print</button>
        <button type="button" @click="openStore">Open</button>
      </div>
    </section>
  </main>
</template>
